Repository DiscordStudy/PublicCalender, pull requests merged in 2024-09, with the labels that each got.

#11 [Feat] 공통 응답 클래스 추가
  src/main/java/discordstudy/calender/global/dto/ApiResponse.java
  src/main/java/discordstudy/calender/global/exception/ErrorCode.java
Labels: 📕 Documentation, 🛠️ feature

#14 [Feat] 커스텀 헤더용 메소드 추가
  src/main/java/discordstudy/calender/global/dto/ApiResponse.java
Labels: 🛠️ feature

#16 [Feat] 예외 처리에 공통 응답을 한다
  src/main/java/discordstudy/calender/global/exception/ApplicationException.java
  src/main/java/discordstudy/calender/global/exception/GlobalExceptionHandler.java
Labels: 🛠️ feature

#18 [Hotfix] ExceptionHandler 적절하게 변경
  src/main/java/discordstudy/calender/global/exception/GlobalExceptionHandler.java
Labels: 🐞 Bug, 💉 Hotfix

#22 [Feat] .env 파일 추가
  .env.sample
  .gitignore
  src/main/resources/application.yaml
Labels: 🛠️ feature

#20 [Feat] Jwt Token 생성 + 토큰을 이용한 로그인 / 회원가입 구현
  build.gradle
  src/main/java/discordstudy/calender/domain/member/controller/MemberController.java
  src/main/java/discordstudy/calender/domain/member/entity/Member.java
  src/main/java/discordstudy/calender/domain/member/repository/MemberRepository.java
  src/main/java/discordstudy/calender/domain/member/service/CustomMemberDetailsService.java
  src/main/java/discordstudy/calender/domain/member/service/MemberService.java
  src/main/java/discordstudy/calender/global/config/SecurityConfig.java
  src/main/java/discordstudy/calender/global/config/jwt/JwtTokenFilter.java
  src/main/java/discordstudy/calender/global/config/jwt/JwtTokenProvider.java
  src/main/java/discordstudy/calender/global/exception/ErrorCode.java
  src/main/resources/application.yaml
Labels: 🛠️ feature

#27 [Feat] 게시판 기능의 CUD를 추가한다
  src/main/java/discordstudy/calender/domain/post/controller/PostController.java
  src/main/java/discordstudy/calender/domain/post/dto/PostRequest.java
  src/main/java/discordstudy/calender/domain/post/dto/PostResponse.java
  src/main/java/discordstudy/calender/domain/post/entity/Hashtag.java
  src/main/java/discordstudy/calender/domain/post/entity/HashtagMap.java
  src/main/java/discordstudy/calender/domain/post/entity/Post.java
  src/main/java/discordstudy/calender/domain/post/repository/HashtagRepository.java
  src/main/java/discordstudy/calender/domain/post/repository/PostRepository.java
  src/main/java/discordstudy/calender/domain/post/service/PostService.java
  src/main/java/discordstudy/calender/domain/post/util/PostConverter.java
  src/main/java/discordstudy/calender/global/entity/BaseTimeEntity.java
  src/main/java/discordstudy/calender/global/exception/ErrorCode.java
Labels: 🛠️ feature
